### ISSUE TITLE
Setting disablewallet=0 and masternodeblsprivkey in conf causes seg fault crash

### ISSUE THREAD

**Issue by willyko** [syscoin/syscoin#407]
Setting masternodeblsprivkey in syscoin.conf automatically turns off wallet functionality.  Attempting to override that with disablewallet=0 causes syscoind to crash.

**Expected behavior**
No crash

**Actual behavior**
```
2020-07-06T23:23:18Z MASTERNODE:
2020-07-06T23:23:18Z Total Memory(MB) 3933 (Total Free 3432) Swap Total(MB) 4095 (Total Free 4095)
2020-07-06T23:23:18Z Total number of physical cores found 2
2020-07-06T23:23:18Z Filling coin cache with masternode UTXOs...
2020-07-06T23:23:18Z Filling coin cache with masternode UTXOs: done in 0ms
Segmentation fault (core dumped)
```
**To reproduce**

Set the following in syscoin.conf
```
disablewallet=0
masternodeblsprivkey=xxx
```

**Comment by sidhujag** [comment]
try in latest code

**Comment by willyko** [comment]
tried the latest; core dump happens at a later point in the log now
```
2020-07-07T08:19:44Z MASTERNODE:
2020-07-07T08:19:44Z Filling coin cache with masternode UTXOs...
2020-07-07T08:19:44Z MASTERNODE:
2020-07-07T08:19:44Z Filling coin cache with masternode UTXOs: done in 0ms
2020-07-07T08:19:44Z   blsPubKeyOperator: 0c6219335fa927d41a9dce984261e09cee3603c19d000e5738b4f07c5bae61e309e09d001de7648550dc4c047129866b
2020-07-07T08:19:44Z fDisableGovernance 0
2020-07-07T08:19:44Z init message: Loading masternode cache...
2020-07-07T08:19:44Z Reading info from mncache.dat...
2020-07-07T08:19:44Z Loaded info from mncache.dat  0ms
2020-07-07T08:19:44Z      Masternodes: meta infos object count: 0
2020-07-07T08:19:44Z Read: Cleaning....
2020-07-07T08:19:44Z      Masternodes: meta infos object count: 0
2020-07-07T08:19:44Z init message: Loading governance cache...
2020-07-07T08:19:44Z Reading info from governance.dat...
2020-07-07T08:19:44Z Loaded info from governance.dat  0ms
2020-07-07T08:19:44Z      Governance Objects: 0 (Proposals: 0, Triggers: 0, Other: 0; Erased: 0), Votes: 0
2020-07-07T08:19:44Z Read: Cleaning....
2020-07-07T08:19:44Z      Governance Objects: 0 (Proposals: 0, Triggers: 0, Other: 0; Erased: 0), Votes: 0
2020-07-07T08:19:44Z Preparing masternode indexes and governance triggers...
2020-07-07T08:19:44Z Masternode indexes and governance triggers prepared  0ms
2020-07-07T08:19:44Z      Governance Objects: 0 (Proposals: 0, Triggers: 0, Other: 0; Erased: 0), Votes: 0
2020-07-07T08:19:44Z init message: Loading fulfilled requests cache...
2020-07-07T08:19:44Z Reading info from netfulfilled.dat...
2020-07-07T08:19:44Z Loaded info from netfulfilled.dat  0ms
2020-07-07T08:19:44Z      Nodes with fulfilled requests: 2
2020-07-07T08:19:44Z Read: Cleaning....
2020-07-07T08:19:44Z      Nodes with fulfilled requests: 2
2020-07-07T08:19:44Z CActiveMasternodeManager::Init -- proTxHash=caa52ba844b5585df2867cfccca59ee0ea270098726e327ceece9380564b7a05, proTx=CDeterministicMN(proTxHash=caa52ba844b5585df2867cfccca59ee0ea270098726e327ceece9380564b7a05, collateralOutpoint=b338ee772d20339ed49ded227729dec0bd90485368d85b1c8e7f43a36ecb1906-1, nOperatorReward=0.000000, state=CDeterministicMNState(nRegisteredHeight=440, nCollateralHeight=105, nLastPaidHeight=459, nPoSePenalty=0, nPoSeRevivedHeight=-1, nPoSeBanHeight=-1, nRevocationReason=0, ownerAddress=tsys1q22zsmlqcgsx9z53hfpck6tt8jtce3p49m54eec, pubKeyOperator=0c6219335fa927d41a9dce984261e09cee3603c19d000e5738b4f07c5bae61e309e09d001de7648550dc4c047129866b, votingAddress=tsys1qnl0fn6frdke7upar4wqc60yzlgzdcwcld23pr5, addr=34.208.148.185:18369, payoutAddress=TMPBsRLKFpW3heWPC1tK4DHmjpsopvXPyx, operatorPayoutAddress=none)
2020-07-07T08:19:44Z CActiveMasternodeManager::Init -- Checking inbound connection to '34.208.148.185:18369'
2020-07-07T08:19:44Z connect() to 34.208.148.185:18369 failed after select(): Connection refused (111)
Segmentation fault (core dumped)
```

**Comment by willyko** [comment]
Was able to gdb and pull the backtrace
```
2020-07-09T21:38:53Z connect() to 34.208.148.185:18369 failed after select(): Connection refused (111)
[New Thread 0x7fffd17d7700 (LWP 62541)]

Thread 10 "s-loadblk" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd2fda700 (LWP 62538)]
0x0000555555a9e4e4 in CActiveMasternodeManager::Init(CBlockIndex const*) ()
(gdb) bt
#0  0x0000555555a9e4e4 in CActiveMasternodeManager::Init(CBlockIndex const*) ()
#1  0x00005555556dd827 in ThreadImport(ChainstateManager&, std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >) ()
#2  0x00005555556ddbc3 in std::_Function_handler<void (), AppInitMain(util::Ref const&, NodeContext&)::{lambda()#8}>::_M_invoke(std::_Any_data const&) ()
#3  0x0000555555705fd1 in void TraceThread<std::function<void ()> >(char const*, std::function<void ()>) ()
#4  0x00005555556d39fa in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(char const*, std::function<void ()>), char const*, AppInitMain(util::Ref const&, NodeContext&)::{lambda()#8}> > >::_M_run() ()
#5  0x00007ffff7e94cb4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7fa8609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007ffff7b84103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by sidhujag** [comment]
try again?

**Comment by willyko** [comment]
no longer reproducible in latest code
